import { Composition, AELayer } from '../types/ae';

export interface ProjectData {
  composition: Composition;
  layers: AELayer[];
}

export const PRESET_PROJECTS: Record<string, { title: string; description: string; data: ProjectData }> = {
  cyberpunk: {
    title: 'Cyberpunk Kinetic (Reels / TikTok)',
    description: 'Títulos dinámicos con resplandor neón, curvas de rebote y separación cromática.',
    data: {
      composition: {
        id: 'comp_cyberpunk',
        name: 'Cyberpunk Kinetic 9:16',
        width: 720,
        height: 1280,
        fps: 30,
        durationFrames: 150, // 5 seconds
        bgColor: '#0B0B12',
        aspectRatio: '9:16',
      },
      layers: [
        {
          id: 'layer_title_top',
          name: 'AFTER EFFECTS',
          type: 'text',
          colorLabel: '#9D95FF',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: true,
          is3D: false,
          inFrame: 0,
          outFrame: 150,
          blendMode: 'lighter',
          transform: {
            position: {
              value: [360, 520, 0],
              isAnimated: true,
              keyframes: [
                { id: 'k1', frame: 0, value: [360, 420, 0], easing: 'bounce' },
                { id: 'k2', frame: 25, value: [360, 520, 0], easing: 'easy-ease' },
                { id: 'k3', frame: 125, value: [360, 520, 0], easing: 'ease-in' },
                { id: 'k4', frame: 150, value: [360, 350, 0], easing: 'linear' },
              ],
            },
            scale: {
              value: [100, 100],
              isAnimated: true,
              keyframes: [
                { id: 'sk1', frame: 0, value: [20, 20], easing: 'bounce' },
                { id: 'sk2', frame: 25, value: [100, 100], easing: 'easy-ease' },
              ],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: true,
              keyframes: [
                { id: 'rk1', frame: 0, value: -15, easing: 'bounce' },
                { id: 'rk2', frame: 25, value: 0, easing: 'easy-ease' },
              ],
            },
            opacity: {
              value: 100,
              isAnimated: true,
              keyframes: [
                { id: 'ok1', frame: 0, value: 0, easing: 'linear' },
                { id: 'ok2', frame: 15, value: 100, easing: 'linear' },
                { id: 'ok3', frame: 135, value: 100, easing: 'linear' },
                { id: 'ok4', frame: 150, value: 0, easing: 'linear' },
              ],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          textData: {
            text: 'AFTER EFFECTS',
            fontSize: 54,
            fontFamily: 'Plus Jakarta Sans',
            color: '#FFFFFF',
            strokeColor: '#9D95FF',
            strokeWidth: 2,
            letterSpacing: 4,
            lineHeight: 1.1,
            align: 'center',
            isBold: true,
            isItalic: false,
            shadowBlur: 25,
            shadowColor: '#9D95FF',
          },
          effects: [
            {
              id: 'eff_glow1',
              type: 'glow',
              name: 'Deep Glow',
              enabled: true,
              params: { radius: 28, intensity: 2.0, color: '#9D95FF' },
            },
          ],
          expression: {
            enabled: false,
            type: 'none',
            freq: 2,
            amp: 10,
          },
        },
        {
          id: 'layer_subtitle',
          name: 'MOBILE POCKET EDITION',
          type: 'text',
          colorLabel: '#38BDF8',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: true,
          is3D: false,
          inFrame: 15,
          outFrame: 150,
          blendMode: 'screen',
          transform: {
            position: {
              value: [360, 600, 0],
              isAnimated: true,
              keyframes: [
                { id: 'sub_p1', frame: 15, value: [360, 680, 0], easing: 'easy-ease' },
                { id: 'sub_p2', frame: 40, value: [360, 600, 0], easing: 'easy-ease' },
              ],
            },
            scale: {
              value: [100, 100],
              isAnimated: false,
              keyframes: [],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: false,
              keyframes: [],
            },
            opacity: {
              value: 100,
              isAnimated: true,
              keyframes: [
                { id: 'sub_o1', frame: 15, value: 0, easing: 'linear' },
                { id: 'sub_o2', frame: 35, value: 100, easing: 'linear' },
              ],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          textData: {
            text: 'MOTION GRAPHICS & VFX',
            fontSize: 22,
            fontFamily: 'Plus Jakarta Sans',
            color: '#38BDF8',
            letterSpacing: 6,
            lineHeight: 1.2,
            align: 'center',
            isBold: true,
            isItalic: false,
            shadowBlur: 15,
            shadowColor: '#38BDF8',
          },
          effects: [],
        },
        {
          id: 'layer_neon_ring',
          name: 'Shape: Neon Star Ring',
          type: 'shape',
          colorLabel: '#F59E0B',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: true,
          is3D: false,
          inFrame: 0,
          outFrame: 150,
          blendMode: 'lighter',
          transform: {
            position: {
              value: [360, 560, 0],
              isAnimated: false,
              keyframes: [],
            },
            scale: {
              value: [100, 100],
              isAnimated: true,
              keyframes: [
                { id: 's_sc1', frame: 0, value: [0, 0], easing: 'bounce' },
                { id: 's_sc2', frame: 35, value: [130, 130], easing: 'easy-ease' },
                { id: 's_sc3', frame: 90, value: [140, 140], easing: 'easy-ease' },
              ],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: true,
              keyframes: [
                { id: 's_r1', frame: 0, value: 0, easing: 'linear' },
                { id: 's_r2', frame: 150, value: 180, easing: 'linear' },
              ],
            },
            opacity: {
              value: 80,
              isAnimated: true,
              keyframes: [
                { id: 's_op1', frame: 0, value: 0, easing: 'linear' },
                { id: 's_op2', frame: 20, value: 85, easing: 'linear' },
              ],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          shapeData: {
            shapeType: 'star',
            fillColor: 'transparent',
            strokeColor: '#9D95FF',
            strokeWidth: 4,
            starPoints: 8,
            width: 380,
            height: 380,
          },
          effects: [
            {
              id: 'eff_glow2',
              type: 'glow',
              name: 'Deep Glow',
              enabled: true,
              params: { radius: 24, intensity: 2.2, color: '#6366F1' },
            },
          ],
          expression: {
            enabled: true,
            type: 'pulse',
            freq: 1.5,
            amp: 8,
          },
        },
        {
          id: 'layer_accent_badge',
          name: 'Shape: Cyber Pill Card',
          type: 'shape',
          colorLabel: '#10B981',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: false,
          is3D: false,
          inFrame: 10,
          outFrame: 150,
          blendMode: 'normal',
          transform: {
            position: {
              value: [360, 560, 0],
              isAnimated: true,
              keyframes: [
                { id: 'pill_p1', frame: 10, value: [360, 580, 0], easing: 'easy-ease' },
                { id: 'pill_p2', frame: 30, value: [360, 560, 0], easing: 'easy-ease' },
              ],
            },
            scale: {
              value: [100, 100],
              isAnimated: true,
              keyframes: [
                { id: 'pill_s1', frame: 10, value: [0, 80], easing: 'bounce' },
                { id: 'pill_s2', frame: 32, value: [100, 100], easing: 'easy-ease' },
              ],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: false,
              keyframes: [],
            },
            opacity: {
              value: 70,
              isAnimated: false,
              keyframes: [],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          shapeData: {
            shapeType: 'rounded_rect',
            fillColor: '#181824',
            strokeColor: '#2D2D42',
            strokeWidth: 2,
            cornerRadius: 24,
            width: 520,
            height: 220,
          },
          effects: [],
        },
        {
          id: 'layer_camera_null',
          name: 'Null: Camera Controller',
          type: 'null',
          colorLabel: '#EF4444',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: false,
          is3D: false,
          inFrame: 0,
          outFrame: 150,
          blendMode: 'normal',
          transform: {
            position: {
              value: [0, 0, 0],
              isAnimated: false,
              keyframes: [],
            },
            scale: {
              value: [100, 100],
              isAnimated: false,
              keyframes: [],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: false,
              keyframes: [],
            },
            opacity: {
              value: 100,
              isAnimated: false,
              keyframes: [],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          effects: [],
          expression: {
            enabled: true,
            type: 'wiggle',
            freq: 1.2,
            amp: 6,
          },
        },
        {
          id: 'layer_vignette_adj',
          name: 'Adjustment: Cinematic Vignette',
          type: 'adjustment',
          colorLabel: '#F97316',
          visible: true,
          locked: true,
          solo: false,
          motionBlur: false,
          is3D: false,
          inFrame: 0,
          outFrame: 150,
          blendMode: 'normal',
          transform: {
            position: { value: [0, 0, 0], isAnimated: false, keyframes: [] },
            scale: { value: [100, 100], isAnimated: false, keyframes: [] },
            scaleLocked: true,
            rotation: { value: 0, isAnimated: false, keyframes: [] },
            opacity: { value: 100, isAnimated: false, keyframes: [] },
            anchorPoint: { value: [0, 0], isAnimated: false, keyframes: [] },
          },
          effects: [
            {
              id: 'eff_vig',
              type: 'vignette',
              name: 'Vignette',
              enabled: true,
              params: { amount: 0.65 },
            },
          ],
        },
      ],
    },
  },
  logoReveal: {
    title: '3D Logo Reveal (16:9)',
    description: 'Rotación con aceleración suave, destello y reveal geométrico moderno.',
    data: {
      composition: {
        id: 'comp_logo_reveal',
        name: 'Logo Reveal 3D',
        width: 1280,
        height: 720,
        fps: 30,
        durationFrames: 120, // 4 seconds
        bgColor: '#0E0E14',
        aspectRatio: '16:9',
      },
      layers: [
        {
          id: 'l_logo_text',
          name: 'STUDIO MOTION',
          type: 'text',
          colorLabel: '#9D95FF',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: true,
          is3D: false,
          inFrame: 20,
          outFrame: 120,
          blendMode: 'normal',
          transform: {
            position: {
              value: [640, 480, 0],
              isAnimated: true,
              keyframes: [
                { id: 'lp1', frame: 20, value: [640, 520, 0], easing: 'easy-ease' },
                { id: 'lp2', frame: 50, value: [640, 480, 0], easing: 'easy-ease' },
              ],
            },
            scale: {
              value: [100, 100],
              isAnimated: false,
              keyframes: [],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: false,
              keyframes: [],
            },
            opacity: {
              value: 100,
              isAnimated: true,
              keyframes: [
                { id: 'lo1', frame: 20, value: 0, easing: 'linear' },
                { id: 'lo2', frame: 45, value: 100, easing: 'linear' },
              ],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          textData: {
            text: 'AE POCKET PRO',
            fontSize: 48,
            fontFamily: 'Plus Jakarta Sans',
            color: '#FFFFFF',
            letterSpacing: 8,
            lineHeight: 1.2,
            align: 'center',
            isBold: true,
            isItalic: false,
            shadowBlur: 20,
            shadowColor: '#6366F1',
          },
          effects: [],
        },
        {
          id: 'l_logo_polygon',
          name: 'Shape: Hexagon Badge',
          type: 'shape',
          colorLabel: '#6366F1',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: true,
          is3D: true,
          inFrame: 0,
          outFrame: 120,
          blendMode: 'lighter',
          transform: {
            position: {
              value: [640, 310, 0],
              isAnimated: false,
              keyframes: [],
            },
            scale: {
              value: [100, 100],
              isAnimated: true,
              keyframes: [
                { id: 'ls1', frame: 0, value: [0, 0], easing: 'bounce' },
                { id: 'ls2', frame: 35, value: [100, 100], easing: 'easy-ease' },
              ],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: true,
              keyframes: [
                { id: 'lr1', frame: 0, value: -180, easing: 'easy-ease' },
                { id: 'lr2', frame: 40, value: 0, easing: 'easy-ease' },
              ],
            },
            opacity: {
              value: 100,
              isAnimated: true,
              keyframes: [
                { id: 'lop1', frame: 0, value: 0, easing: 'linear' },
                { id: 'lop2', frame: 20, value: 100, easing: 'linear' },
              ],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          shapeData: {
            shapeType: 'polygon',
            fillColor: '#1A1A2E',
            strokeColor: '#9D95FF',
            strokeWidth: 6,
            width: 240,
            height: 240,
          },
          effects: [
            {
              id: 'eff_glow_poly',
              type: 'glow',
              name: 'Deep Glow',
              enabled: true,
              params: { radius: 24, intensity: 2.0, color: '#9D95FF' },
            },
          ],
        },
        {
          id: 'l_center_symbol',
          name: 'Shape: Inner Star',
          type: 'shape',
          colorLabel: '#38BDF8',
          visible: true,
          locked: false,
          solo: false,
          motionBlur: true,
          is3D: false,
          inFrame: 10,
          outFrame: 120,
          blendMode: 'lighter',
          transform: {
            position: {
              value: [640, 310, 0],
              isAnimated: false,
              keyframes: [],
            },
            scale: {
              value: [100, 100],
              isAnimated: true,
              keyframes: [
                { id: 'iss1', frame: 10, value: [0, 0], easing: 'bounce' },
                { id: 'iss2', frame: 45, value: [100, 100], easing: 'easy-ease' },
              ],
            },
            scaleLocked: true,
            rotation: {
              value: 0,
              isAnimated: true,
              keyframes: [
                { id: 'isr1', frame: 10, value: 120, easing: 'easy-ease' },
                { id: 'isr2', frame: 60, value: 0, easing: 'easy-ease' },
              ],
            },
            opacity: {
              value: 100,
              isAnimated: true,
              keyframes: [
                { id: 'iso1', frame: 10, value: 0, easing: 'linear' },
                { id: 'iso2', frame: 30, value: 100, easing: 'linear' },
              ],
            },
            anchorPoint: {
              value: [0, 0],
              isAnimated: false,
              keyframes: [],
            },
          },
          shapeData: {
            shapeType: 'star',
            fillColor: '#38BDF8',
            strokeColor: '#FFFFFF',
            strokeWidth: 2,
            starPoints: 4,
            width: 110,
            height: 110,
          },
          effects: [],
          expression: {
            enabled: true,
            type: 'pulse',
            freq: 2,
            amp: 6,
          },
        },
      ],
    },
  },
};
